version: '3.9'

services:
  redis:
    image: redis
    ports:
      - 6379:6379

  mongodb:
    image: mongo:5.0
    ports:
      - 27017:27017
    volumes:
      - ~/apps/mongo:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=surl
      - MONGO_INITDB_ROOT_PASSWORD=surl-83948

  s-url:
    image: s-url:latest
    ports:
      - 8080:8080
      - 5005:5005
    depends_on:
      - "redis"
    environment:
      - spring.profiles.active=prod
      - spring.redis.host=redis
      - spring.redis.port=6379
      - spring.data.mongodb.host=  mongodb
      - spring.data.mongodb.port=27017
      - spring.data.mongodb.authentication-database=admin
      - spring.data.mongodb.username=surl
      - spring.data.mongodb.password=surl-83948
      - spring.data.mongodb.database=s-url