version: '3.8'

services:
  redis:
    image: redis
    ports:
      - 6379:6379

  s-url:
    image: s-url:latest
    ports:
      - 8080:8080
      - 5005:5005
    depends_on:
      - "redis"
    environment:
      - "SPRING_PROFILES_ACTIVE=prod"
      - "SPRING_REDIS_HOST=redis"
      - "SPRING_REDIS_PORT=6379"